## Let's clean some real data

In [9]:
import pandas as pd
import matplotlib.pyplot as plt

Police set but without guard rails:
[Link to data source at Stanford](https://openpolicing.stanford.edu/data/)

Original inspiration:
[Here you can find the same type of data but sanitized and with a similar exercise.](https://github.com/justmarkham/pycon-2018-tutorial)

In [10]:
result = pd.read_csv(r'D:\repos\dataengineering\yg821jf8611_il_statewide_2020_04_01.csv\il_statewide_2020_04_01.csv', index_col=0, low_memory=False )

In [11]:
result.size
result.shape

result.sample(40)

,date,time,location,beat,subject_age,subject_race,subject_sex,department_id,department_name,type,...,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_make,vehicle_year,raw_DriverRace,raw_ReasonForStop,raw_TypeOfMovingViolation,raw_ResultOfStop
raw_row_number,,,,,,,,,,,,,,,,,,,,,
4521459,2014-06-14,23:45:00,60616,0133,NaN,white,female,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,HONDA,2004.0,1,1,4,1
1826867,2012-12-25,08:40:00,30035,01,NaN,black,female,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,DODG,2012.0,2,1,1,1
3161170,2013-10-26,18:00:00,62278,13,NaN,white,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,DODG,2011.0,1,1,1,2
5994125,2014-09-30,06:56:00,62221,0001,NaN,asian/pacific islander,male,13775.0,SHILOH POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,BMW,2013.0,5,1,1,2
1097782,2012-10-14,08:30:00,60443,46,NaN,black,female,13155.0,TINLEY PARK POLICE,vehicular,...,False,False,NaN,Equipment,HONDA,2004.0,2,2,0,1
1380746,2012-11-09,23:56:00,60435,14,NaN,white,male,13945.0,JOLIET POLICE,vehicular,...,False,False,NaN,Moving Violation: Lane Violation,CHRYSLER,1991.0,1,1,2,1
8699345,2016-01-02,18:01:00,60655,825,NaN,white,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Equipment,FORD,2015.0,1,2,0,3
4618620,2014-09-15,17:43:00,61265,0000,NaN,white,male,13766.0,COAL VALLEY POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,Ford,2011.0,1,1,1,1
11850374,2017-02-21,17:08:00,60045,D1,NaN,asian/pacific islander,female,13478.0,LAKE BLUFF POLICE,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,Mercedes-Benz (MERZ),2015.0,5,1,4,1
3685393,2013-02-18,12:10:00,85283,8,NaN,hispanic,male,13011.0,ORLAND PARK POLICE,vehicular,...,False,False,NaN,Equipment,HYUN,2005.0,4,2,0,1
4875303,2014-11-02,21:43:00,60164,LEY,NaN,hispanic,female,13172.0,FRANKLIN PARK POLICE,vehicular,...,True,False,consent,Equipment,Jeep,1999.0,4,2,0,3
2927988,2013-03-15,01:25:00,60827,1,NaN,black,male,13046.0,HOMEWOOD POLICE,vehicular,...,False,False,NaN,License Plate/Registration,HONDA,1992.0,2,3,0,1
10430768,2016-11-13,03:30:00,60046,Winthrop H,NaN,white,male,13500.0,WINTHROP HARBOR POLICE,vehicular,...,False,False,NaN,Moving Violation: Lane Violation,CHEVROLET,2001.0,1,1,2,2
3522372,2013-12-16,20:08:00,60062,820,NaN,white,male,13027.0,MORTON GROVE POLICE,vehicular,...,False,False,NaN,Moving Violation: Lane Violation,Infiniti (INFI),2003.0,1,1,2,3
8484201,2016-07-11,06:22:00,60089,32,NaN,white,female,13467.0,BUFFALO GROVE POLICE,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,SAAB,2008.0,1,1,4,3
5220635,2014-01-04,03:30:00,60624,03,NaN,black,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,True,True,NaN,Moving Violation: Lane Violation,CHEV,2007.0,2,1,2,1
9720917,2016-07-25,17:09:00,60527,MCCPD,NaN,white,female,13034.0,MCCOOK POLICE,vehicular,...,False,False,NaN,License Plate/Registration,ACURA,2013.0,1,3,0,2
10257953,2016-11-23,18:57:00,60504,1,NaN,white,female,13430.0,ST. CHARLES POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,DODGE,2013.0,1,1,1,2
6318743,2015-01-07,04:28:00,60505,6,NaN,hispanic,female,13413.0,AURORA POLICE,vehicular,...,True,False,NaN,Moving Violation: Traffic Sign or Signal,LINCOLN,2001.0,4,1,4,1
1746363,2012-09-17,22:35:00,72204,13,NaN,black,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,True,NaN,Equipment,CHEV,1999.0,2,2,0,1
10993906,2017-11-09,15:45:00,NaN,713,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Equipment,VOLKSWAGEN,2016.0,2,2,0,3
2227367,2013-09-01,17:13:00,60532,01-15,NaN,white,male,13414.0,BATAVIA POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,CHEVROLET,1999.0,1,1,1,2
9136289,2016-03-04,19:48:00,60478,2,NaN,black,female,13164.0,HAZEL CREST POLICE,vehicular,...,False,False,NaN,Equipment,CHEVY,2000.0,2,2,0,2
594349,2012-06-03,10:14:00,60803,1,NaN,black,female,13177.0,EVERGREEN PARK POLICE,vehicular,...,False,False,NaN,License Plate/Registration,JEEP,2001.0,2,3,0,1
8592725,2016-12-11,23:28:00,60641,1623,NaN,black,female,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Equipment,SUZUKI,2004.0,2,2,0,1
5562802,2014-03-29,09:57:00,60473,E,NaN,hispanic,male,13030.0,MIDLOTHIAN POLICE,vehicular,...,False,False,NaN,Moving Violation: Other,Ford,2012.0,4,1,6,1
12601743,2017-12-16,20:25:00,47933,0011,NaN,white,male,13885.0,VERMILION COUNTY SHERIFF,vehicular,...,False,False,NaN,Equipment,NaN,2005.0,1,2,0,3
5777336,2014-06-07,23:12:00,60067,8110,NaN,white,female,13010.0,PALATINE POLICE,vehicular,...,False,False,NaN,License Plate/Registration,CHEV,2005.0,1,3,0,1
12500324,2017-02-16,01:02:00,60140,FLOAT,NaN,white,female,13428.0,SLEEPY HOLLOW POLICE,vehicular,...,True,True,NaN,Moving Violation: Other,FORD,2014.0,1,1,6,1
5427617,2014-03-06,14:20:00,60409,3,NaN,black,female,13041.0,LANSING POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,Chevrolet,2006.0,2,1,1,3
11310418,2017-05-28,15:33:00,60423,S,NaN,white,female,13949.0,FRANKFORT POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,DODGE,2013.0,1,1,1,2
1702422,2012-07-31,10:00:00,62899,10,NaN,white,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Commercial Vehicle,FREIGHTLINER,2011.0,1,4,0,3
12046545,2017-07-27,15:56:00,60487,M302,NaN,white,female,13941.0,MOKENA POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,DODG,2005.0,1,1,1,3
2742836,2013-11-26,05:01:00,60643,3,NaN,black,female,13177.0,EVERGREEN PARK POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,GMC,2003.0,2,1,1,3
2265069,2013-08-07,17:32:00,60641,1,NaN,white,female,13207.0,BERWYN POLICE,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,FORD,2011.0,1,1,4,1
5783710,2014-11-15,00:00:00,60477,A,NaN,white,female,13009.0,PALOS HEIGHTS POLICE,vehicular,...,False,False,NaN,Equipment,Dodge,2001.0,1,2,0,3
11903571,2017-04-05,11:02:00,60659,224,NaN,white,male,13040.0,LINCOLNWOOD POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,TOYOTA,2012.0,1,1,1,1
7222130,2015-12-03,09:01:00,60643,15,NaN,black,female,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,License Plate/Registration,LEXUS,2006.0,2,3,0,2
5124232,2014-01-29,15:24:00,62522,09,NaN,white,male,13991.0,ILLINOIS STATE POLICE,vehicular,...,False,False,NaN,Moving Violation: Speed,CHEV,2013.0,1,1,1,1
1202902,2012-09-22,21:13:00,60053,12,NaN,white,male,13189.0,COOK COUNTY FOREST PRESERVE POLICE,vehicular,...,False,False,NaN,License Plate/Registration,MITS,2009.0,1,3,0,1

In [12]:
result.columns

Index(['date', 'time', 'location', 'beat', 'subject_age', 'subject_race',
       'subject_sex', 'department_id', 'department_name', 'type', 'violation',
       'citation_issued', 'warning_issued', 'outcome', 'contraband_found',
       'contraband_drugs', 'contraband_weapons', 'search_conducted',
       'search_person', 'search_vehicle', 'search_basis', 'reason_for_stop',
       'vehicle_make', 'vehicle_year', 'raw_DriverRace', 'raw_ReasonForStop',
       'raw_TypeOfMovingViolation', 'raw_ResultOfStop'],
      dtype='object')

In [13]:
result.head()

,date,time,location,beat,subject_age,subject_race,subject_sex,department_id,department_name,type,...,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_make,vehicle_year,raw_DriverRace,raw_ReasonForStop,raw_TypeOfMovingViolation,raw_ResultOfStop
raw_row_number,,,,,,,,,,,,,,,,,,,,,
1,2012-09-15,10:20:00,60641,1611,NaN,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Traffic Sign or Signal,CHRYSLER,2004.0,4,1,4,1
2,2012-09-15,10:20:00,60189,1912,NaN,white,female,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Lane Violation,LEXUS,1999.0,1,1,2,1
3,2012-09-15,10:20:00,60638,815,NaN,hispanic,female,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Other,WHITE GMC (BEGIN. MODEL YEAR 1988),2010.0,4,1,6,1
4,2012-09-15,10:20:00,60638,925,NaN,white,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Other,CHEVROLET,2008.0,1,1,6,1
5,2012-09-15,10:21:00,NaN,2032,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,NaN,Moving Violation: Other,DODGE,2007.0,2,1,6,1

In [14]:
result.dtypes

date                          object
time                          object
location                      object
beat                          object
subject_age                  float64
subject_race                  object
subject_sex                   object
department_id                float64
department_name               object
type                          object
violation                     object
citation_issued                 bool
warning_issued                  bool
outcome                       object
contraband_found              object
contraband_drugs              object
contraband_weapons            object
search_conducted              object
search_person                 object
search_vehicle                object
search_basis                  object
reason_for_stop               object
vehicle_make                  object
vehicle_year                 float64
raw_DriverRace                 int64
raw_ReasonForStop              int64
raw_TypeOfMovingViolation      int64
raw_ResultOfStop               int64
dtype: object

In [15]:
result.count()

date                         12748173
time                         12737036
location                     12624518
beat                         12518026
subject_age                      8316
subject_race                 12747428
subject_sex                  12747842
department_id                12748173
department_name              12748173
type                         12748173
violation                    12748163
citation_issued              12748173
warning_issued               12748173
outcome                      12748172
contraband_found               574565
contraband_drugs               574519
contraband_weapons             574556
search_conducted             12731391
search_person                12731391
search_vehicle               12731256
search_basis                   189648
reason_for_stop              12748163
vehicle_make                 12417506
vehicle_year                 12735863
raw_DriverRace               12748173
raw_ReasonForStop            12748173
raw_TypeOfMovingViolation    12748173
raw_ResultOfStop             12748173
dtype: int64

In [16]:
result.isnull().sum()

date                                0
time                            11137
location                       123655
beat                           230147
subject_age                  12739857
subject_race                      745
subject_sex                       331
department_id                       0
department_name                     0
type                                0
violation                          10
citation_issued                     0
warning_issued                      0
outcome                             1
contraband_found             12173608
contraband_drugs             12173654
contraband_weapons           12173617
search_conducted                16782
search_person                   16782
search_vehicle                  16917
search_basis                 12558525
reason_for_stop                    10
vehicle_make                   330667
vehicle_year                    12310
raw_DriverRace                      0
raw_ReasonForStop                   0
raw_TypeOfMovingViolation           0
raw_ResultOfStop                    0
dtype: int64

OK so far it´s similar
But now we want only records with a contraband found.

In [17]:
contraband = result.loc[result['contraband_found'].isnull()==False]

In [26]:
contraband.head()

,date,time,location,beat,subject_age,subject_race,subject_sex,department_id,department_name,type,...,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_make,vehicle_year,raw_DriverRace,raw_ReasonForStop,raw_TypeOfMovingViolation,raw_ResultOfStop
raw_row_number,,,,,,,,,,,,,,,,,,,,,
36,2012-01-01,01:13:00,60653,724,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,consent,License Plate/Registration,BUICK,2004.0,2,3,0,3
37,2012-01-01,01:14:00,60707,2531,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,NaN,License Plate/Registration,CADILLAC,2000.0,2,3,0,1
80,2012-01-01,07:33:00,60608,924,NaN,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,NaN,Moving Violation: Traffic Sign or Signal,CHEVROLET,1997.0,4,1,4,1
89,2012-01-01,09:05:00,60609,914,NaN,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,consent,Moving Violation: Traffic Sign or Signal,CHEVROLET,1984.0,4,1,4,1
100,2012-01-01,10:30:00,60612,1532,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,consent,Moving Violation: Other,CHEVROLET,2011.0,2,1,6,1

In [25]:
contraband.isnull().sum()

date                              0
time                            276
location                       2603
beat                          11671
subject_age                  574560
subject_race                      9
subject_sex                       7
department_id                     0
department_name                   0
type                              0
violation                         0
citation_issued                   0
warning_issued                    0
outcome                           0
contraband_found                  0
contraband_drugs                 46
contraband_weapons                9
search_conducted                  0
search_person                     0
search_vehicle                    0
search_basis                 386191
reason_for_stop                   0
vehicle_make                  28486
vehicle_year                    514
raw_DriverRace                    0
raw_ReasonForStop                 0
raw_TypeOfMovingViolation         0
raw_ResultOfStop                  0
dtype: int64

Lets remove some coded data that just encode text fields. Warning, these are the type of fields we would like to keep or make by encoding for ML or statistics.

In [28]:
cleaned_contra = contraband.drop(['raw_DriverRace', 'raw_ReasonForStop', 'raw_TypeOfMovingViolation','raw_ResultOfStop'], axis = 'columns')
cleaned_contra.shape

(574565, 24)

In [30]:
cleaned_contra.head()

,date,time,location,beat,subject_age,subject_race,subject_sex,department_id,department_name,type,...,contraband_found,contraband_drugs,contraband_weapons,search_conducted,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_make,vehicle_year
raw_row_number,,,,,,,,,,,,,,,,,,,,,
36,2012-01-01,01:13:00,60653,724,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,False,True,True,True,consent,License Plate/Registration,BUICK,2004.0
37,2012-01-01,01:14:00,60707,2531,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,False,True,True,True,True,NaN,License Plate/Registration,CADILLAC,2000.0
80,2012-01-01,07:33:00,60608,924,NaN,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,False,True,True,True,NaN,Moving Violation: Traffic Sign or Signal,CHEVROLET,1997.0
89,2012-01-01,09:05:00,60609,914,NaN,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,False,True,True,True,consent,Moving Violation: Traffic Sign or Signal,CHEVROLET,1984.0
100,2012-01-01,10:30:00,60612,1532,NaN,black,male,13194.0,CHICAGO POLICE,vehicular,...,False,False,False,True,True,True,consent,Moving Violation: Other,CHEVROLET,2011.0

There is subject_age field thats not empty, worth keeping?

In [34]:
aged = cleaned_contra[cleaned_contra.subject_age.notna()]
aged

,date,time,location,beat,subject_age,subject_race,subject_sex,department_id,department_name,type,...,contraband_found,contraband_drugs,contraband_weapons,search_conducted,search_person,search_vehicle,search_basis,reason_for_stop,vehicle_make,vehicle_year
raw_row_number,,,,,,,,,,,,,,,,,,,,,
2451080,2013-11-15,20:37:00,60628,NaN,26.0,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,NaN,True,True,True,NaN,License Plate/Registration,CHEV,1991.0
2456055,2013-07-04,10:48:00,60628,NaN,33.0,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,NaN,True,True,True,NaN,Moving Violation: Seat Belt,GMC,1999.0
2465107,2013-03-17,00:47:00,60622,NaN,32.0,hispanic,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,NaN,True,True,True,NaN,License Plate/Registration,DODG,2000.0
2465365,2013-03-28,11:49:00,60624,NaN,77.0,black,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,NaN,True,True,True,NaN,License Plate/Registration,BUIC,1997.0
2465477,2013-03-20,23:21:00,60181,NaN,31.0,white,male,13194.0,CHICAGO POLICE,vehicular,...,True,True,NaN,True,True,True,NaN,License Plate/Registration,CHEV,1998.0

That was not very exiting. Age is not very prevalent. We can actually see all.


### Well any prejudices?

In [21]:
result[result['subject_race'] == 'white'].search_conducted.value_counts(normalize=True)

False    0.963831
True     0.036169
Name: search_conducted, dtype: float64

In [22]:
print('blacks')

result[result['subject_race'] == 'black'].search_conducted.value_counts(normalize=True)

blacks

False    0.931292
True     0.068708
Name: search_conducted, dtype: float64

In [23]:
result.groupby('subject_race').search_conducted.value_counts(normalize=True)

subject_race            search_conducted
asian/pacific islander  False               0.984643
                        True                0.015357
black                   False               0.931292
                        True                0.068708
hispanic                False               0.937724
                        True                0.062276
other                   False               0.964709
                        True                0.035291
white                   False               0.963831
                        True                0.036169
Name: search_conducted, dtype: float64

In [24]:
output_contra = cleaned_contra.groupby('subject_race').contraband_found.value_counts(normalize=True)
output_contra

subject_race            contraband_found
asian/pacific islander  False               0.813277
                        True                0.186723
black                   False               0.779934
                        True                0.220066
hispanic                False               0.845401
                        True                0.154599
other                   False               0.844551
                        True                0.155449
white                   False               0.782014
                        True                0.217986
Name: contraband_found, dtype: float64

### So some not very conslusive results


Any other metrics?
Age? Sex? Car age? (And how would you handle that one?)
Visualize?